// app/layout.js
import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}



